[project]
name = "pyclipmgr"
version = "5.0.2"
authors = [
  { name="Sudo Man", email="supertechman@yahoo.com" },
]
description = "his lib check for your machine's platform and use system commands to contact with clipboard (copy or paste) in python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GPL License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/mohammed-saleh2007/py-clip-mgr"
Issues = "https://github.com/mohammed-saleh2007/py-clip-mgr/issues"